# Generated by Django 2.2 on 2020-10-24 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20201024_0823'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favorites',
        ),
    ]
