# Generated by Django 2.2 on 2020-10-24 08:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapp', '0003_delete_favorites'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='fav_picture',
            field=models.ManyToManyField(blank=True, related_name='fav_picture', to=settings.AUTH_USER_MODEL, verbose_name='Избранное фото'),
        ),
    ]
